(cl:in-package gps_reader-msg)
(cl:export '(HEADER-VAL
          HEADER
          ACCEL-VAL
          ACCEL
          GYRO-VAL
          GYRO
          MAG-VAL
          MAG
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          HEADING-VAL
          HEADING
          GROUND_SPEED-VAL
          GROUND_SPEED
          FIXTYPE-VAL
          FIXTYPE
          IMUDEGC-VAL
          IMUDEGC
          SIV-VAL
          SIV
          PDOP-VAL
          PDOP
          HZ-VAL
          HZ
          GPSTIME-VAL
          GPSTIME
          RTCTIME-VAL
          RTCTIME
))